name: nb-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter
  - nbconvert
  - ipykernel
  - aiohttp
  - cftime
  - cf-units
  - dask
  - dask-gateway
  - dask-jobqueue
  - distributed
  - fsspec
  - geocat-comp
  - geopandas
  - intake
  - intake-esm
  - matplotlib
  - nc-time-axis
  - nest-asyncio
  - h5netcdf
  - netcdf4
  - numpy
  - pandas
  - pyproj
  - pystac-client
  - rasterio
  - requests
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - tqdm
  - uxarray
  - xarray
  - xarray-regrid
  - xhistogram
  - pip:
      - pelicanfs